In [1]:
from okx_quant.utils.config_utils import ConfigUtils
from okx_quant.data.kline import Kline

config_path = '../config/config.toml'
config_utils = ConfigUtils(config_path)
api_config = config_utils.api_config
config = config_utils.config

In [2]:
kline = Kline(api_config, config)
kline

In [3]:
df = kline.get_history_kline('BTC-USDT', '2022-01-01', '2025-02-14', period='1D')
len(df)

Error fetching data: HTTPSConnectionPool(host='www.dojqutmbiuuo.com', port=443): Max retries exceeded with url: /api/v5/market/history-candles?after=1649606400000&bar=1D&before=1640966400000&instId=BTC-USDT&limit=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

TypeError: object of type 'NoneType' has no len()

In [4]:
df

,timestamp,open,high,low,close,vol,volCcy,volCcyQuote,confirm
0,2024-01-01 01:00:00,42597.3,42653.6,42471.1,42610.4,161.767319,6.887182e+06,6.887182e+06,1.0
1,2024-01-01 02:00:00,42610.5,42720.0,42533.3,42659.1,144.478166,6.160296e+06,6.160296e+06,1.0
2,2024-01-01 03:00:00,42659.7,42695.8,42583.3,42612.1,204.109771,8.701271e+06,8.701271e+06,1.0
3,2024-01-01 04:00:00,42615.8,42680.8,42505.8,42559.0,171.815118,7.317645e+06,7.317645e+06,1.0
4,2024-01-01 05:00:00,42555.2,42666.5,42514.1,42514.4,190.932037,8.131934e+06,8.131934e+06,1.0
...,...,...,...,...,...,...,...,...,...
3630,2024-05-31 07:00:00,68317.8,68526.9,68250.1,68357.9,80.633579,5.513149e+06,5.513149e+06,1.0
3631,2024-05-31 08:00:00,68358.5,68491.5,68277.1,68473.8,143.137096,9.787824e+06,9.787824e+06,1.0
3632,2024-05-31 09:00:00,68473.8,68659.3,68312.6,68455.4,538.025199,3.686996e+07,3.686996e+07,1.0
3633,2024-05-31 10:00:00,68455.5,68748.7,68433.4,68542.6,395.430676,2.711824e+07,2.711824e+07,1.0
3634,2024-05-31 11:00:00,68542.5,68631.6,68490.0,68533.0,122.117041,8.372084e+06,8.372084e+06,1.0